### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by mario-kr** [matthiasbeyer/task-hookrs#24]
Hello,
As I was trying to read the documentation, and I noticed there is barely one. I'd like to propose to at least write examples of how to use task-hookrs to write such a hook, and write some docs for the functions which may be used by other programmers, or how to use them.

**Comment by matthiasbeyer** [comment]
I will add documentation as soon as I find enough time. Thanks for opening this.

**Comment by matthiasbeyer** [comment]
See #19
