### ISSUE TITLE
import fails when using in hooks

### ISSUE THREAD

**Issue by mario-kr** [matthiasbeyer/task-hookrs#25]
Hello,
in the function import::import() you are expecting to get a JSON-Array, however, taskwarrior only sends line separated JSON-Objects, so it doesnt work anymore. I have tested it out with the configuration options json.array and json.depends.array. I dont know what the latter does, but the former only affects the task export/task import command.

**Comment by matthiasbeyer** [comment]
I will have a look at this in ~1 week., thanks a lot for reporting!

**Comment by matthiasbeyer** [comment]
This should be fixed with #26 I guess, so I will close this now.
