### ISSUE TITLE
RFE: Support UDAs

### ISSUE THREAD

**Issue by mathstuf** [matthiasbeyer/task-hookrs#31]
It'd be nice to have UDA support. Not sure how best to do it, but probably just return `Value` bit for them? Would be really nice to query the configuration for UDA descriptions and offer them as actual types.

**Comment by matthiasbeyer** [comment]
That'd be a nice thing, yes.

I will consider this for the next version.

**Comment by matthiasbeyer** [comment]
Querying the configuration to support type-conversion is a bit complicated IMHO. It could be done, and I guess I will be able to model the UDA support in a way so that I can add the UDA-type-conversion support later, but it won't be a goal in the first step, I guess.

**Comment by mathstuf** [comment]
I wonder if it could work like hypre where there's a macro to define a new Header. Here, there'd be a UDA macro which would then fetch it's value in a type-safe way.

**Comment by matthiasbeyer** [comment]
UDA support was just merged in #58
