### ISSUE TITLE
Relicense? 

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/task-hookrs#34]
Hi,

I thought about the issue with the license (documented in [this reddit](https://www.reddit.com/r/rust/comments/4xd195/ann_filters_a_library_to_build_predicates_and/d6efxz2))

We would relicense with MIT and Apache2 - as suggested. I'm just generally asking if everyone is okay with it, I will then ask @cmr to send one of his famous relicensing-PRs (as you can [see here](https://github.com/nathan7/libfringe/pull/26)).

So, are you guys okay with relicensing and if not - why?

@erickt 
@mario-kr

**Comment by mario-kr** [comment]
I'm OK with it

**Comment by erickt** [comment]
I am as well.

**Comment by matthiasbeyer** [comment]
As described in https://github.com/matthiasbeyer/filters/issues/9 we might consider MPL. I will wait how the discussion in https://github.com/matthiasbeyer/filters/issues/9 turns out and then decide and ask you (inside this issue) again.

**Comment by mario-kr** [comment]
As for me, don't bother. As long as it stays Open Source, and one can easily work on it via GitHub or similar, It's fine.

**Comment by matthiasbeyer** [comment]
@mario-kr alright. You'd still have to acknowledge the license change in the appropriate PR, to be legally safe.

**Comment by erickt** [comment]
MPL would be fine with me as well.
