### ISSUE TITLE
Development mailing list link redirects to a 404 notice

### ISSUE THREAD

**Issue by adam-gaia** [matthiasbeyer/task-hookrs#6]
Please add more information regarding the development mailing list. The only reference I can find are in the default issue and PR templates:

```
<!--
IMPORTANT NOTICE

Github is only used for CI right now, main development continues on the
mailinglist.

Please send issues and pull requests (either via `git request-pull` or `git
format-patch` + `git send-email`) to
[the imag mailinglist](https://imag-pim.org/mailinglist/).
-->
```

The specified webpage (https://imag-pim.org/mailinglist/) directs to a page in Japanese. When put through google translate, the page appears to be a 404 notice.

I would like to contribute to this project, however am not sure how to proceed.

**Comment by matthiasbeyer** [comment]
Hah, I forgot to remove the link here. Thanks for notifying me!

**Comment by adam-gaia** [comment]
No worries. Thanks for clearing this up so quickly!
