### ISSUE TITLE
Please consider tagging a new version

### ISSUE THREAD

**Issue by adam-gaia** [matthiasbeyer/task-hookrs#7]
Hello,
I'm trying to use `task::set_tags()` from the latest release `v0.7.0`. I've noticed that the function signature has changed from
```rust
pub fn set_tags<T, K>(&mut self, new: Option<T>) ...
```
in tag `v0.7.0` to
```rust
pub fn set_tags<T>(&mut self, new: Option<T>) ...
```
on the master branch (note the dropping of generic `K`).
`0.7.0` appears to have been tagged in 2019. I would appreciate a new tagged version including this update to `set_tags()`.

Until then, I'm specifying a specific commit in my Cargo.toml.
```toml
task-hookrs = { git = "https://github.com/matthiasbeyer/task-hookrs.git", rev = "8a2ff6ad1c913d58dfd5cad4a33f2ddef8ea43e6" }
```

**Comment by matthiasbeyer** [comment]
I did some cleanup and replaced "failure" with "thiserror". This is now released as 0.8.0!

Thanks for pinging me about this! :tada:
