### ISSUE TITLE
How can I set an optional field on a Task which currently has no value for it.

### ISSUE THREAD

**Issue by maralorn** [matthiasbeyer/task-hookrs#71]
Take for example the field `project`.

If the field is set, I can modify it with
```rust
task.project_mut().map(|x| *x = "my_project.subproject".to_owned());
```
but what, if `task.project()` is `None`? If I don't overlook anything, I can`t set a new project for the existing task.

**Comment by matthiasbeyer** [comment]
This is correct. We should change the signatures to `&mut Option<...>` I guess!
