### ISSUE TITLE
`set_tags<T, K>` is generic over unused type `K`

### ISSUE THREAD

**Issue by kdheepak** [matthiasbeyer/task-hookrs#82]
Can you clarify why this is generic over `K`? What is the type of `K` here?

https://github.com/matthiasbeyer/task-hookrs/blob/8a0f8f73fd6d1f97327b3582c42646a0d3310aee/src/task.rs#L470

This `K` is not used in the function body so this is not needed, right? The rust compiler is currently not able to infer the types when calling this function.

**Comment by matthiasbeyer** [comment]
Fixed in master.

Can you use the master branch or should I fire up a release right away?
You're always welcome to use master for now and as soon as you're about to release your software, I can prepare a release!

**Comment by kdheepak** [comment]
Wow thanks for the quick fix! Yeah, I can use `master`. No hurry about making a release :)
