### ISSUE TITLE
`UDAValue` being a negative integer causes failure to import 

### ISSUE THREAD

**Issue by kdheepak** [matthiasbeyer/task-hookrs#84]
If you have the following `test.json`:

```json
[ 
{"id":1,"depends":"faa5b76b-26f5-4488-a1d5-dc0451e9d0a5","description":"TASK 1","entry":"20201024T004013Z","modified":"20201024T005507Z","status":"pending","uuid":"b79adfc3-f7b6-454a-8b28-2a163459488b","urgency":-5}, 
{"id":2,"description":"TASK 2","entry":"20201024T004105Z","modified":"20201024T004105Z","status":"pending","uuid":"faa5b76b-26f5-4488-a1d5-dc0451e9d0a5","urgency":8}, 
{"id":0,"description":"tests","end":"20201024T084807Z","entry":"20201024T010139Z","modified":"20201024T084808Z","status":"deleted","uuid":"c4bc86d9-b6ed-42d0-8243-757f03fcfcf2","urgency":0}, 
{"id":0,"description":"pooooop","end":"20201024T084810Z","entry":"20201024T010144Z","modified":"20201024T084812Z","status":"deleted","uuid":"b6452b89-5cea-46cc-82b8-381d502417b6","urgency":0} 
] 
```

Then the following rust code fails:

```rust
use task_hookrs::import::import;
use task_hookrs::task::Task;


fn main() {
    let data = std::fs::read_to_string("./test.json").unwrap();
    let imported = import(data.as_bytes()).unwrap();
    dbg!(imported);
}
```

with this error:

```plaintext
called `Result::unwrap()` on an `Err` value: Error("invalid type: integer `-5`, expected an UDA value like a string, float or int", line: 2, column: 215)
```

I believe this is because `UDAValue` is set as string, float or _unsigned_ int 

https://github.com/matthiasbeyer/task-hookrs/blob/2953cf02b3c56b164a44e95fac5aae6f38954620/src/uda.rs#L22-L23

and urgency as parsed as a `UDAValue` (?).

I think 1) `urgency` should always be parsed as a floating point value, and 2) `UDAValue`s can be `string`, `numeric`, `date` or `duration`. The first one is more critical to resolve at the moment than the second.

Thoughts?

**Comment by kdheepak** [comment]
See https://github.com/kdheepak/taskwarrior-tui/issues/23 for more information / context.

**Comment by matthiasbeyer** [comment]
Sounds legit. Do you want to submit a PR to fix this?

**Comment by kdheepak** [comment]
Thanks for the quick reply! Sure! Would you like me to make both changes?

1) I think we should add a new field called `urgency` to `Task` that is a `f64` and parse that separately by adding a block here:

https://github.com/matthiasbeyer/task-hookrs/blob/2953cf02b3c56b164a44e95fac5aae6f38954620/src/task.rs#L743-L748

2) Extend `UDAValue` to handle `string`, `numeric`, `date` and `duration` based on https://taskwarrior.org/docs/udas.html.

I can do this as two PRs, if you'd like.

**Comment by matthiasbeyer** [comment]
Would be awesome!

**Comment by kdheepak** [comment]
I've started working on the second PR but `serde` is going over my head at the moment. Specifically, I'm not able to convert a string to a `Date` in the `src/uda.rs` file.

**Comment by kdheepak** [comment]
I'm closing this issue since the bug is resolved. Having UDAValue support durations would be a enhancement but is not critical.
