### ISSUE TITLE
Custom priority values are not supported

### ISSUE THREAD

**Issue by kdheepak** [matthiasbeyer/task-hookrs#87]
Beginning with taskwarrior 2.4.3, priority is no longer a core attribute.

https://taskwarrior.org/docs/priority.html

Users can create custom priorities like so:

```
# ~/.taskrc
uda.priority.values=U,H,M,L
color.uda.priority.U=color1
urgency.uda.priority.U.coefficient=15.0
```

I think priority can be handled the same way UDA is handled. I'll submit a PR for this.

**Comment by matthiasbeyer** [comment]
You are doing good work here, I really appreciate what you're doing! Keep going!

We should maybe add some taskwarrior-compat information to the repository. For example, we should mention which taskwarrior version is supported by this crate and which is explicitely not (or via feature flags in the Cargo.toml?).
Maybe there's a way to add CI tests for this, even?

**Comment by kdheepak** [comment]
That's a good idea to add taskwarrior-compat information and tests! I'll do that. 

This particular change will work regardless of which taskwarrior version one is using. In previous version the priority could only be one of few (`H`, `M`, `L`) but now can be arbitrarily any string. But your point stands for other changes that I might be introducing.

Are you suggesting feature flags in Cargo.toml to support older versions of taskwarrior?

**Comment by matthiasbeyer** [comment]
On 14-02-2021 09:45:35, Dheepak Krishnamurthy wrote:
> Are you suggesting feature flags in Cargo.toml to support older versions of taskwarrior? 

Yes, but not necessarily if there's a better approach.

I think taskwarrior 2.5.0 should be the minimum supported version, I guess that
was the one I used when initially developing this crate.

I'm not sure what can be done to make this library support multiple versions of
taskwarrior at once.
Maybe some clever tricks with generics and zero-sized structs? That sounds like
an idea, but I might be not thinking everything through at the moment!

**Comment by kdheepak** [comment]
Sounds interesting! I'll definitely keep it in mind.
